spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shortener
    username: postgres
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
server:
  port: 8080
