apiVersion: v1
kind: ConfigMap
metadata:
  name: url-shortener-config

data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "shortener_db"

  REDIS_HOST: "redis"
  REDIS_PORT: "6379"

  KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"

  ANALYTICS_SERVICE_URL: "http://analytics-service:8081"